### ISSUE TITLE
0.4.81 pnpm install error 

### ISSUE THREAD

**Issue by BG7ZAG** [k0swe/adif-parser-ts#488]
![image](https://github.com/k0swe/adif-parser-ts/assets/16408650/581250fb-71f2-4180-b8b7-5926d2224aa4)

husky install error

**Comment by floZx** [comment]
Yes now impossible to install the module:

```
npm install adif-parser-ts 

npm ERR! code 127
npm ERR! path /Users/florian/dev/xxxxxxx/node_modules/adif-parser-ts
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: husky: command not found
```

**Comment by xylo04** [comment]
I'm seeing this in my project too. I'm not sure what changed. If necessary, I can take Husky completely out of this repo.

**Comment by BG7ZAG** [comment]
> I'm seeing this in my project too. I'm not sure what changed. If necessary, I can take Husky completely out of this repo.

try 
```
  "scripts": {
    "prepare": "husky install",
  }
```

**Comment by xylo04** [comment]
Husky wasn't doing anything terribly useful, anyway. This should be fixed as of https://github.com/k0swe/adif-parser-ts/releases/tag/v0.4.82
